import{S as f,i as a}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const p="47458933-146f1ea8ad921328f8e999f88",m="https://pixabay.com/api/";function g(s){return fetch(`${m}?key=${p}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&per_page=30`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}function h(s){const t=document.querySelector("#gallery"),o=s.map(({webformatURL:n,largeImageURL:e,tags:r,likes:i,views:l,comments:u,downloads:d})=>`
                 <li> <a href="${e}">
                <img src="${n}" alt="${r}" width="360px" height="200px" class="image"/>
                </a>
                <div class = "info">
                <div class="info-div"> <p class="section"> Likes: </p> <p class="result" > ${i} </p> </div>
                <div class="info-div"> <p class="section"> Views: </p> <p class="result"> ${l} </p> </div>
                <div class="info-div"> <p class="section"> Comments: </p> <p class="result"> ${u} </p> </div>
                <div class="info-div"> <p class="section"> Downloads: </p> <p class="result"> ${d} </p> </div>
                 </div>
                </li>
               `).join("");t.insertAdjacentHTML("beforeend",o)}function y(){gallery.innerHTML=""}function c(s){document.querySelector("#toggle-div").classList.toggle("hidden",!s)}const v=document.querySelector("#search-form"),L=document.querySelector("#search-input"),S=new f("#gallery a",{captionsData:"alt",captionDelay:250});v.addEventListener("submit",s=>{s.preventDefault();const t=L.value.trim();if(!t){a.error({title:"Error",message:"Search field cannot be empty!"});return}y(),c(!0),g(t).then(o=>{if(c(!1),!o.hits.length){a.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(o.hits),S.refresh()}).catch(o=>{c(!1),a.error({title:"Error",message:"Something went wrong. Please try again later."})})});
//# sourceMappingURL=index.js.map
